version: '3.9'
name: automation-stack
services:
  tailscale:
    image: tailscale/tailscale:stable
    hostname: "${TAILSCALE_HOSTNAME}"
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
    volumes:
      - tailscale-state:/var/lib/tailscale
    networks:
      - automation
    command:
      - /bin/sh
      - -c
      - |
        if [ -z "${TS_AUTHKEY}" ]; then
          echo 'TS_AUTHKEY must be provided' >&2
          exit 1
        fi
        tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/tmp/tailscaled.sock --tun=userspace-networking &
        until tailscale --socket=/tmp/tailscaled.sock status >/dev/null 2>&1; do
          sleep 0.5
        done
        tailscale --socket=/tmp/tailscaled.sock up --authkey=${TS_AUTHKEY} --hostname=${TAILSCALE_HOSTNAME} --ssh
        tailscale --socket=/tmp/tailscaled.sock serve reset
        tailscale --socket=/tmp/tailscaled.sock serve --bg tcp 80 flowfuse:3000
        tailscale --socket=/tmp/tailscaled.sock serve --bg tcp 1880 node-red:1880
        tailscale --socket=/tmp/tailscaled.sock serve --bg tcp 1883 hivemq:1883
        tailscale --socket=/tmp/tailscaled.sock serve --bg tcp 1884 hivemq-edge:1883
        tailscale --socket=/tmp/tailscaled.sock serve --bg tcp 8080 hivemq:8080
        tailscale --socket=/tmp/tailscaled.sock serve --bg tcp 8088 ignition:8088
        tailscale --socket=/tmp/tailscaled.sock serve --bg tcp 8123 monster-mq:8080
        tailscale --socket=/tmp/tailscaled.sock serve --bg tcp 9000 timebase:8011
        tailscale --socket=/tmp/tailscaled.sock serve --bg tcp 9001 timebase:8013
        tailscale --socket=/tmp/tailscaled.sock serve --bg tcp 9002 timebase-historian:8011
        tailscale --socket=/tmp/tailscaled.sock serve --bg tcp 9003 timebase-historian:8013
        tailscale --socket=/tmp/tailscaled.sock serve --bg tcp 9086 influxdb:8086
        tailscale --socket=/tmp/tailscaled.sock serve --bg tcp 9090 grafana:3000
        tailscale --socket=/tmp/tailscaled.sock serve --bg tcp 5432 postgres:5432
        wait
    restart: unless-stopped
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - automation
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - automation
    restart: unless-stopped
  flowfuse:
    image: flowfuse/flowfuse:latest
    depends_on:
      - postgres
      - redis
    environment:
      FF_PROJECTS_DIR: /var/lib/flowfuse
      FF_STORAGE__TYPE: localfs
      FF_DB__CLIENT: pg
      FF_DB__PG__HOST: postgres
      FF_DB__PG__USER: ${POSTGRES_USER}
      FF_DB__PG__PASSWORD: ${POSTGRES_PASSWORD}
      FF_DB__PG__DATABASE: ${POSTGRES_DB}
      FF_REDIS__HOST: redis
    volumes:
      - flowfuse-data:/var/lib/flowfuse
    networks:
      - automation
    restart: unless-stopped
  node-red:
    image: nodered/node-red:3.1
    environment:
      NODE_RED_ENABLE_PROJECTS: 'true'
    volumes:
      - node-red-data:/data
    networks:
      - automation
    restart: unless-stopped
  monster-mq:
    build:
      context: https://github.com/vogler75/monster-mq.git
    networks:
      - automation
    restart: unless-stopped
  hivemq:
    image: hivemq/hivemq-ce:2023.1
    environment:
      HIVEMQ_ALLOW_ANONYMOUS: 'true'
    volumes:
      - hivemq-data:/opt/hivemq/data
    networks:
      - automation
    restart: unless-stopped
  hivemq-edge:
    image: hivemq/hivemq-edge:latest
    volumes:
      - hivemq-edge-data:/opt/hivemq-edge/data
    networks:
      - automation
    restart: unless-stopped
  ignition:
    image: kcollins/ignition:8.1
    environment:
      GATEWAY_ADMIN_PASSWORD: ignitionAdmin42!
    volumes:
      - ignition-data:/usr/local/share/ignition/data
    networks:
      - automation
    restart: unless-stopped
  timebase:
    image: finos/timebase-server:6.1
    environment:
      TB_HEAP: 2G
    volumes:
      - timebase-data:/timebase
    networks:
      - automation
    restart: unless-stopped
  timebase-historian:
    image: finos/timebase-server:6.1
    environment:
      TB_HEAP: 2G
    volumes:
      - timebase-historian-data:/timebase
    networks:
      - automation
    restart: unless-stopped
  influxdb:
    image: influxdb:2.7
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_ADMIN_USER}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_RETENTION: ${INFLUXDB_RETENTION}
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    networks:
      - automation
    restart: unless-stopped
  grafana:
    image: grafana/grafana:10.4.3
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - automation
    restart: unless-stopped
networks:
  automation:
    driver: bridge
volumes:
  tailscale-state:
  postgres-data:
  redis-data:
  flowfuse-data:
  node-red-data:
  hivemq-data:
  hivemq-edge-data:
  ignition-data:
  timebase-data:
  timebase-historian-data:
  influxdb-data:
  influxdb-config:
  grafana-data:
